version: '3.8'
services:
  frontend:
    image: kutaui/personal:latest
    networks:
      - watchtower-network
    container_name: portfolio_ blog
    ports:
      - "4321:4321"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    restart: always
    networks:
      - watchtower-network
    command: --cleanup portfolio_blog

networks:
  watchtower-network:
    external: true
